spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}-test
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true